HOST = localhost
PORT = 8080
URL = http://$(HOST):$(PORT)/index.html
SERVER_SCRIPT = src/main/server.py

run-server:
	@echo "Запуск сервера..."
	python3 $(SERVER_SCRIPT)

ab-test:
	@echo "Запуск нагрузочного тестирования с помощью ab..."
	ab -n 1000 -c 10 $(URL)

wrk-test:
	@echo "Запуск нагрузочного тестирования с помощью wrk..."
	wrk -t12 -c400 -d30s $(URL)

test-ab: run-server ab-test

test-wrk: run-server wrk-test

ci-ab:
	@echo "CI: Запуск теста с ab..."
	$(MAKE) ab-test

ci-wrk:
	@echo "CI: Запуск теста с wrk..."
	$(MAKE) wrk-test

github-actions:
	@echo "Настройка GitHub Actions..."
	@echo "GitHub Actions могут запускать тесты через цели 'ci-ab' или 'ci-wrk'."

.PHONY: run-server ab-test wrk-test test-ab test-wrk ci-ab ci-wrk github-actions
